### ISSUE TITLE
UI/UX 

### ISSUE THREAD

**Issue by bednarz1990** [CoyoteNET/CoyoteNET-frontend#4]
Hi guys,
I would like to know what are we going to do with UI. Are we going to create UI from scratch with absolutely new views. What is our plan with that issue ? Any suggestions ?
In my opinion, we should create some mockups or concept of UI. 

Regards :) 👍

**Comment by dotNETSanta** [comment]
I'd want to suggest trying to improve current 4p's layout by for example: using dark theme as a default.

**Comment by bednarz1990** [comment]
That's fine. Let's make 4P great again. Anyway I am not master of CSS. Who is willing to help us  ?

**Comment by silvuss** [comment]
@bednarz1990 If it comes about CSS, I can deal with it. In general, I may try to work both on UI and UX, unless e.g. @dotNETSanta would disallow.

**Comment by miniMax18** [comment]
@silvuss. We have to use SASS for more convenience at now and future. I think You know.

**Comment by silvuss** [comment]
@miniMax18 I have no objection – it may be SASS, it may be LESS. I would have objection both in case of Bootstrap and dealing with CSS mainly from within JavaScript.
