### ISSUE TITLE
Appveyor build failing

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-frontend#5]
### Problem

Our current CI, Appveyor, reports that this repository fails to build. @dotNETSanta may you see why is that?

### Expected behavior

The project pass building in Appveyor.

### Current behavior

The project fails to build in Appveyor.

**Comment by miniMax18** [comment]
"If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command." @silvuss I think this is because pipeline.yml or whatever format file, setting is not plug.  Those are only default settings.

**Comment by dotNETSanta** [comment]
Well, here we are: https://ci.appveyor.com/project/dotNETSanta/coyotenet-frontend

It's seems to NOT be nice, but it works

If you want to change building / testing process then PR here: https://github.com/CoyoteNET/CoyoteNET-frontend/blob/master/appveyor.yml

**Comment by miniMax18** [comment]
That is it :)

**Comment by silvuss** [comment]
@dotNETSanta The issue is completed, but tell, what did you mean by "It's seems that it is not NOT nice, but it works"?

**Comment by dotNETSanta** [comment]
@silvuss 

Appveyor showed some warnings and I wasn't really sure about it, but at the end it passed.

https://ci.appveyor.com/project/dotNETSanta/coyotenet-frontend/builds/23521967

**Comment by silvuss** [comment]
@dotNETSanta OK, I see them, but I don't know what they are about, I don't know npm. Keep them in mind, please – just in case.

**Comment by dotNETSanta** [comment]
@silvuss 

After this merge https://github.com/CoyoteNET/CoyoteNET-frontend/commit/b31eec03e7324ccbb0b2f3602dae5eb3e576aa28

That's the new result: https://ci.appveyor.com/project/dotNETSanta/coyotenet-frontend

**Comment by silvuss** [comment]
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

> warning "react-scripts > pnp-webpack-plugin > ts-pnp@1.0.1" has unmet peer dependency "typescript@*".

Hm, only two warnings. Maybe, the code could be somehow patched to get rid of the first or both? Some tips maybe:
- https://stackoverflow.com/questions/46928390/what-does-has-unmet-peer-dependency-mean-when-installing-a-package-with-yarn
- https://github.com/yarnpkg/yarn/issues/4595
